env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

freebsd_instance:
  image_family: freebsd-12-1

package:
  timeout_in: 90m
  pkg_upgrade_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - pkg upgrade -y
  pkg_install_script:
    - pkg install -y lang/ghc devel/hs-cabal-install 
  portsnap_script:
    - portsnap  --interactive fetch 
    - portsnap extract
  build_package_script:
    - env BATCH=1 PACKAGES=`pwd` make -C devel/hs-ShellCheck-static package
  check_dir_script:
    - ls -ltRr
  binaries_artifacts:
    path: "hs-ShellCheck*"
